# PCA on the 7 metrics

## Load library

```{r}
# Multivariate Analysis (PCA & PERMANOVA)
library(dimensio)
library(vegan)

# Linear Mixed Models & Diagnostics
library(lme4)
library(lmerTest) # For p-values in lmer
library(DHARMa)   # Residual diagnostics
library(car)      # Type 3 Anova

# Data & Visualisation
library(readr)
library(dplyr)
library(emmeans)
library(ggplot2)
library(ggbeeswarm)
```

## Set working directory

```{r}
setwd("~/Desktop/simon_lasio/data/behavior and activity/pca")
```

## Load and prepare data

```{r}
# === Paramètres ===
file <- "mega.csv"
delim <- ","                                      
decimal_mark <- "."             

# === 1) Lecture robuste du fichier ===
# read_delim permet de gérer decimal_mark et détecte mieux les colonnes

data <- read_delim(file,
                   delim = delim,
                   locale = locale(decimal_mark = decimal_mark),
                   trim_ws = TRUE,
                   col_names = TRUE,
                   progress = FALSE,
                   guess_max = 2000)

colnames(data) <- c("Year", "Petridish_number", "Antibiotic", "Reinoculation",
                    "Treatment", "Mean_prop_time_moving", "Mean_Average_Speed", "Mean_dist", "nb_bump","nb_avoidance",
                    "nb_head2head", "nb_touch", "nb_antennal_interaction")


data$Antibiotic <- factor(data$Antibiotic)
data$Reinoculation <- factor(data$Reinoculation)

data$Antibiotic <- factor(data$Antibiotic, levels = c("zero", "low", "high"))
data$Reinoculation <- relevel(data$Reinoculation, ref = "no")
```

### PCA for Treatment

```{r}
data2 <- data[, !(names(data) %in% c("Antibiotic", "Reinoculation", "Year", "nb_antennal_interaction",  "Petridish_number"))]
head(data2)

X <- dimensio::pca(data2, center = TRUE, scale = FALSE, sup_quali = "Treatment")
eig <- get_eigenvalues(X)
eig
screeplot(X, cumulative = TRUE)

viz_variables(X)


viz_individuals(
  x = X,
  extra_quali = data2$Treatment,
  color = c("#4477AA", "#EE6677", "#528833", "#9477AA", "#AE6677", "#E28833"), # Custom color scheme
  legend = list(x = "topright") ,
  ellipse = list(type = "tolerance", level = 0.95)
)


# === 3) MULTIVARIATE STATISTICS (PERMANOVA & BETADISPER) ===
set.seed(123) 
# A. Data Preparation for Vegan
stats_matrix <- data2[, sapply(data2, is.numeric)]

# Calculate Euclidean Distance Matrix // We use Euclidean because PCA preserves Euclidean distances.
dist_matrix <- vegdist(stats_matrix, method = "euclidean")

# B. Check for Homogeneity of Dispersion (Betadisper)
# This tests: "Do some groups have more variable behavior than others?" If this is significant, the groups have different shapes/spreads.

dispersion_mod <- betadisper(dist_matrix, data$Treatment)

# Visualize the dispersion
plot(dispersion_mod, main = "Multivariate Dispersion (Betadisper)")
boxplot(dispersion_mod, main = "Distance to Centroid per Group")

# BETADIASPER RESULT - Test significance of dispersion
permu_treat <- permutest(dispersion_mod, permutations = 999)
permu_treat

# C. PERMANOVA (Adonis2)
# This tests: "Are the centers of the groups significantly different?"
set.seed(123) # Ensures results are reproducible
# Test 1: Simple effect of Treatment
ado_treat <- adonis2(dist_matrix ~ Treatment, strata = data$Year, data = data, method = "euclidean")
ado_treat

```

### PCA for Antibiotic

```{r}
data3 <- data[, !(names(data) %in% c("Treatment", "Reinoculation","Year", "nb_antennal_interaction",  "Petridish_number"))]
data3$Antibiotic <- as.character(data3$Antibiotic)
head(data3)

X <- dimensio::pca(data3, center = TRUE, scale = FALSE, sup_quali = "Antibiotic")

get_eigenvalues(X)
screeplot(X, cumulative = TRUE)
biplot(X, type = "form", labels = "variables")
biplot(X, type = "covariance", labels = "variables")
viz_variables(X)

viz_individuals(
  x = X,
  extra_quali = data3$Antibiotic,
  color = c("#4477AA", "#EE6677", "#228833", "#9477AA", "#AE6677", "#E28833"), # Custom color scheme
  #symbol = c(1, 2, 3, 4, 5, 6, 7), # Custom symbols
  legend = list(x = "topright") ,
  ellipse = list(type = "tolerance", level = 0.95)
)


# === 3) MULTIVARIATE STATISTICS (PERMANOVA & BETADISPER) ===
set.seed(123) 
# A. Data Preparation for Vegan
stats_matrix <- data3[, sapply(data3, is.numeric)]

# Calculate Euclidean Distance Matrix // We use Euclidean because PCA preserves Euclidean distances.
dist_matrix <- vegdist(stats_matrix, method = "euclidean")

# B. Check for Homogeneity of Dispersion (Betadisper)
# This tests: "Do some groups have more variable behavior than others?" If this is significant, the groups have different shapes/spreads.
dispersion_mod <- betadisper(dist_matrix, data$Antibiotic)

# Visualize the dispersion
plot(dispersion_mod, main = "Multivariate Dispersion (Betadisper)")
boxplot(dispersion_mod, main = "Distance to Centroid per Group")

# BETADIASPER RESULT - Test significance of dispersion
permu_ant <- permutest(dispersion_mod, permutations = 999)
permu_ant
# C. PERMANOVA (Adonis2)
# This tests: "Are the centers of the groups significantly different?"
set.seed(123) # Ensures results are reproducible
# Test 1: Simple effect of Antibiotic
ado_ant <- adonis2(dist_matrix ~ Antibiotic, strata=data$Year, data = data, method = "euclidean")
ado_ant

```

### PCA for réinoculation

```{r}
data4 <- data[, !(names(data) %in% c("Antibiotic", "Treatment", "Year", "nb_antennal_interaction",  "Petridish_number"))]
head(data4)

X <- dimensio::pca(data4, center = TRUE, scale = FALSE, sup_quali = "Reinoculation")

get_eigenvalues(X)
screeplot(X, cumulative = TRUE)
biplot(X, type = "form", labels = "variables")
biplot(X, type = "covariance", labels = "variables")
viz_variables(X)

viz_individuals(
  x = X,
  extra_quali = data4$Reinoculation,
  color = c("#4477AA", "#EE6677", "#228833", "#9477AA", "#AE6677", "#E28833"), # Custom color scheme
  #symbol = c(1, 2, 3, 4, 5, 6, 7), # Custom symbols
  legend = list(x = "topright") ,
  ellipse = list(type = "tolerance", level = 0.95)
)


set.seed(123) 
# A. Data Preparation for Vegan
stats_matrix <- data3[, sapply(data3, is.numeric)]
# Calculate Euclidean Distance Matrix // We use Euclidean because PCA preserves Euclidean distances.
dist_matrix <- vegdist(stats_matrix, method = "euclidean")


# B. Check for Homogeneity of Dispersion (Betadisper)
# This tests: "Do some groups have more variable behavior than others?" If this is significant, the groups have different shapes/spreads.
dispersion_mod <- betadisper(dist_matrix, data$Reinoculation)

# Visualize the dispersion
plot(dispersion_mod, main = "Multivariate Dispersion (Betadisper)")
boxplot(dispersion_mod, main = "Distance to Centroid per Group")

# BETADIASPER RESULT - Test significance of dispersion
permu_reino <- permutest(dispersion_mod, permutations = 999)
permu_reino

# C. PERMANOVA (Adonis2)
# This tests: "Are the centers of the groups significantly different?"
set.seed(123) # Ensures results are reproducible
# Test 1: Simple effect of Antibiotic
ado_reino <- adonis2(dist_matrix ~ Reinoculation, strata=data$Year, data = data, method = "euclidean")
ado_reino

```

### PCA on the PC1

#### extract the PC1

```{r}
data5 <- data[, !(names(data) %in% c("Antibiotic", "Reinoculation", "Year", "nb_antennal_interaction",  "Petridish_number"))]
head(data5)

X <- dimensio::pca(data5, center = TRUE, scale = FALSE, sup_quali = "Treatment")

get_eigenvalues(X)
screeplot(X, cumulative = TRUE)
biplot(X, type = "form", labels = "variables")
biplot(X, type = "covariance", labels = "variables")
viz_variables(X)

pca_scores <- get_coordinates(X)

combined_interaction_data <- pca_scores$F1

data$combined <- combined_interaction_data
```

#### LMM on PC1

```{r}
hist(data$combined, breaks = 10)
qqnorm(data$combined)


model_lmm <- lmer(combined ~ Antibiotic * Reinoculation + (1 | Year), data = data)


res <- simulateResiduals(model_lmm)
plot(res)
testDispersion(res)
testUniformity(res) # This is the standard test for residual distribution


s1 <- summary(model_lmm)
s1
a1 <- Anova(model_lmm, type=3)
a1

```

### Visualisation

```{r}

emm <- emmeans(model_lmm, ~ Antibiotic * Reinoculation)
all_pairwise <- pairs(emm)
emm_df <- as.data.frame(emm)

p1 <- ggplot() +
  # A. IC
  geom_rect(data = emm_df,
            aes(xmin = as.numeric(Antibiotic) - 0.3,
                xmax = as.numeric(Antibiotic) + 0.3,
                ymin = lower.CL,  
                ymax = upper.CL,  
                fill = Reinoculation),
            alpha = 0.3, 
            position = position_dodge(width = 0.8),
            show.legend = FALSE) + 

  # B. Predicted mean
  geom_errorbar(data = emm_df,
                aes(x = Antibiotic, 
                    ymin = emmean, 
                    ymax = emmean,
                    color = Reinoculation),
                width = 0.5, 
                position = position_dodge(width = 0.8), 
                size = 1.2) +
  
  # C. Raw data
  geom_beeswarm(data = data,
                aes(x = Antibiotic, 
                    y = combined, 
                    color = Reinoculation),
                dodge.width = 0.8, 
                cex = 1.2,        # Taille de dispersion
                size = 1.5,       # Taille des points
                alpha = 0.4) +    # Transparence 

  theme_bw() +
  labs(y = "PC1 value", 
       x = "Antibiotic dose",
       color = "Reinoculation",
       fill = "Reinoculation") +
  ggtitle("PC1")

print(p1)



```
## Save the plot 
```{r}
ggsave("PC1_Plot.pdf", p1, width = 12, height = 8)
```

# Save the result in a .txt file

```{r}


sink("pca_result.txt", split = TRUE)

cat("PCA on the 7 metrics\n")

cat("eigenvalue treatment")
eig

cat("PCA for treatment\n")
permu_treat
ado_treat

cat("PCA for antibiotic\n")
permu_ant
ado_ant

cat("PCA for réinoculation\n")
permu_reino
ado_reino

cat("Linear mixed model on PC1\n")

a1 
s1 

sink()

```
