# Load packages

```{r}
library(readr)
library(dplyr)
library(survival)
library(survminer)
library(ggplot2)
```

# Set working directory

```{r}
setwd("~/Desktop/simon_lasio/data/survival analysis")

```

# Read and prepare data

```{r}
surv_individual <- read_delim(
  "surv_individual_export.csv",
  delim = ";",
  locale = locale(decimal_mark = ","),
  trim_ws = TRUE,
  col_names = TRUE,
  progress = FALSE,
  guess_max = 2000
)

surv_individual <- surv_individual %>%
  mutate(
    Treatment = factor(Treatment),
    Treatment = relevel(Treatment, ref = "zero_no"),
    Antibiotic = factor(Antibiotic, levels = c("zero", "low", "high")),
    Reinoculation = factor(Reinoculation),
    Reinoculation = relevel(Reinoculation, ref = "no"),
    Year = factor(Year),
    Petridish_number = factor(Petridish_number))
```

# Fit a survival curve using the Kaplan-Meier method

```{r}
fit_ant <- survfit(Surv(time, status) ~ Antibiotic, type = "kaplan-meier", data=surv_individual)
fit_reino <- survfit(Surv(time, status) ~ Reinoculation, type = "kaplan-meier", data=surv_individual)
fit_inter <- survfit(Surv(time, status) ~ Treatment, type = "kaplan-meier", data=surv_individual)
```

# Log-Rank Test

```{r}
surv_diff_ant <- survdiff(Surv(time, status) ~ Antibiotic, data = surv_individual)
surv_diff_reino <- survdiff(Surv(time, status) ~ Reinoculation, data = surv_individual)
surv_diff_inter <- survdiff(Surv(time, status) ~ Treatment, data = surv_individual)
```

# Create the plots

```{r}
p_ant <- ggsurvplot(
  fit_ant,
  #title = "Impact of antibiotic on survival",
  pval = TRUE,
  pval.size = 5,
  pval.method = TRUE,
  conf.int = FALSE,
  surv.scale = "percent",
  xlab = "Time [h]",
  ylab = "Survival probability",
  ggtheme = theme_survminer(base_size = 8, base_family = "Helvetica"),
  legend.title = "Antibiotic dose",
  palette = "Dark2",
  linewidth = 1,
  alpha = 0.65, 
)
p_ant$plot <- p_ant$plot +
  geom_vline(xintercept = 70, linetype = "dotted", size = 0.7) +
  annotate(
    "text",
    x = 70, y = 0.20,           # adjust y to be at top of plot
    label = "Re-inoculation",      # this will act as legend label
    angle = 90,
    vjust = -0.5,
    color = "black",
    size = 3
  )

p_ant


p_reino <- ggsurvplot(
  fit_reino,
  title = "Impact of réinoculation on survival",
  pval = TRUE,
  pval.size = 7,
  pval.method = TRUE,
  conf.int = FALSE,
  surv.scale = "percent",
  xlab = "Time [h]",
  ylab = "Survival probability",
  ggtheme = theme_survminer(base_size = 8, base_family = "Helvetica"),
  legend.title = "Réinoculation (yes/no)",
  palette = "Dark2",
  linewidth = 1.0,
  alpha = 0.8
)
p_reino$plot <- p_reino$plot +
  geom_vline(xintercept = 70, linetype = "dotted", size = 0.7) +
  annotate(
    "text",
    x = 70, y = 0.20,           # adjust y to be at top of plot
    label = "Réinoculation",      # this will act as legend label
    angle = 90,
    vjust = -0.5,
    color = "black",
    size = 3
  )

p_reino


p_inter <- ggsurvplot(
  fit_inter,
  title = "Impact of antibiotics and re-inoculation on survival",
  pval = TRUE,
  pval.size = 6,
  pval.method = TRUE,
  conf.int = FALSE,
  surv.scale = "percent",
  xlab = "Time [h]",
  ylab = "Survival probability",
  ggtheme = theme_survminer(base_size = 8, base_family = "Helvetica"),
  legend.title = "Treatment",
  palette = "Dark2",
  linewidth = 1.0,
  alpha = 0.8
)
p_inter$plot <- p_inter$plot +
  geom_vline(xintercept = 70, linetype = "dotted", size = 0.7) +
  annotate(
    "text",
    x = 70, y = 0.20,           # adjust y to be at top of plot
    label = "Réinoculation",      # this will act as legend label
    angle = 90,
    vjust = -0.5,
    color = "black",
    size = 3
  )
p_inter
```

# Save the plot

```{r}
ggsave("p_ant.pdf",   p_ant$plot,   width = 9, height = 5)
ggsave("p_reino.pdf", p_reino$plot, width = 8, height = 4)
ggsave("p_inter.pdf", p_inter$plot, width = 8, height = 4)
```

# Save the result in a .txt file

```{r}
output_file <- "survival_result.txt"
sink(output_file)

fit_ant
fit_reino
fit_inter
surv_diff_ant
surv_diff_ant$pvalue
surv_diff_reino
surv_diff_reino$pvalue
surv_diff_inter
surv_diff_inter$pvalue

sink()
```


# Justifying the joining of zero and low 
```{r}

survdiff(Surv(time, status) ~ Antibiotic, data = subset(surv_individual, Antibiotic %in% c("zero", "low")))


```
