---
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  results = "hide",
  fig.show = "hide",
  message = FALSE,
  warning = FALSE
)
```

# Load packages
```{r}
library(readr)
library(here)
library(lme4)
library(lmerTest)
library(ggplot2)
library(car)
library(dplyr)

set.seed(67)
options(contrasts = c("contr.sum", "contr.poly"))
```

# Read result and load a dataframe
```{r}
path <- here::here("qpcr", "data", "rawdata")
myFiles <- list.files(path= path, 
                      recursive = FALSE, pattern = "\\.csv$", full.names = TRUE)

empty = data.frame() # make empty variable which will be filled with data from the loop

for(x in myFiles){
  t <- read_delim(x,
                  delim = ";",
                  locale = locale(decimal_mark = "."),
                  trim_ws = TRUE,
                  col_names = TRUE,
                  progress = FALSE,
                  guess_max = 2000)
  t <- t[, c("Sample", "Target", "Cq")]
  names(t)[1:3] <- c("Sample.Name","Target.Name","Ct")
  t$Ct <- as.numeric(t$Ct) 
  t$Target.Name <- factor(t$Target.Name)
  t$Sample.Name <- factor(t$Sample.Name)
  
  t.m <- aggregate(Ct ~ Sample.Name + Target.Name, data = t, FUN = mean, na.action = na.pass) 
  t.sd <- aggregate(Ct ~ Sample.Name + Target.Name, data = t, FUN = sd, na.action = na.pass)
  t <- merge(t.m, t.sd, by=c("Sample.Name","Target.Name")) # merge Ct and SD values

  water <- t[t$Sample.Name == "WATER",] 
  targets = levels(t$Target.Name)
  newt = data.frame()
  for (i in targets){
    TempWater=water[water$Target.Name ==i,] 
    if (is.na(TempWater[1,3]) == T) {TempWater[1,3]=41} 
    TempData=t[t$Target.Name==i,]
    for (ii in 1:nrow(TempData)){ 
      if (is.na(TempData[ii,3])==F) {
        if (TempData[ii,3]>=TempWater[1,3]) {TempData[ii,3]=NA} } 
    }
    newt = rbind(newt, TempData)
  }
  # remove negative and positive samples
  newt <- newt[newt$Sample.Name!= "positive control",]
  newt <- newt[newt$Sample.Name!= "WATER",]

  empty <- dplyr::bind_rows(empty, newt)
}

empty <- as.data.frame(empty) # change 'empty' to data frame
names(empty)[1:4] <- c("Sample_ID","Target","Ct","SD")
```

# Load data
```{r}
cts <- empty
```

# Preparation of the data
```{r}
cts$X <- NULL
colnames(cts) <- c("Bee_ID", "Target", "Ct", "SD") # rename columns for better work

# rename levels of targets
cts$Target <- as.factor(cts$Target)

path2 <- here::here("qpcr", "data")

treatments <- read_delim(file.path(path2, "LasioExtractions.csv"),
                         delim = ";",
                         locale = locale(decimal_mark = "."),
                         trim_ws = TRUE,
                         col_names = TRUE,
                         progress = FALSE,
                         guess_max = 2000)

dt <- merge(cts,treatments, by.x="Bee_ID", by.y="SampleID") # adds Treatment and exp#

# turn remained SD values to NA if Ct = NA
dt$SD[is.na(dt$Ct)] <- NA

# check proportion of not quality data
poor <- dt[dt$SD > 0.7 & dt$Ct < 30,]
poor <- poor[!is.na(poor$Ct),]
a = nrow(poor)
b = nrow(dt)
(a/b)*100   #1 % of data can be doubtful
```

## Calculate Copy number for each target

$$
\text{Copy number} = (\text{Efficiency}^\text{Intercept - C^t} ) \times \text{dilution factor}
$$

```{r}
#Values from calculation made in the lab earlier 
dt$copynum <- ((2.0570179 ^ (36.6020484 - dt$Ct)) * 200)
dt$copynum <- round(dt$copynum)
```

## Exploratory plot to discover the data

```{r}
dt$Treatment <- factor(dt$Treatment, levels= c( "BeforeExperiment", "Ctr","AntLow","AntLow+hom","AntHigh","AntHigh+hom", "GutHomFeedingSolution(SecondStep)", "GutHomogenate", "GlycerolPBScontrol(FirstStep)", "ControlFeedingSolution(SecondStep)"))
dt$Treatment <- relevel(dt$Treatment, ref = "Ctr")
dt$Replicate <- factor(dt$Replicate)


p1 <- ggplot(dt, aes(x = Treatment, y = copynum))+ 
  geom_boxplot(outlier.shape = NA) +
  geom_point(aes(colour=Treatment), shape = 16, size = 3, show.legend = FALSE, alpha = 0.7) +
  scale_x_discrete()+ 
  scale_y_log10()+
  annotation_logticks(base = 10, sides = "l", scaled = TRUE,
                      short = unit(0.05, "cm"), mid = unit(0.1, "cm"), long = unit(0.2, "cm"),
                      colour = "black", size = 0.5, linetype = 1, alpha = 1, color = NULL)+

theme_bw()
print(p1)
```
##Descriptive stats 

```{r}
dt_clean <- dt %>% 
  filter(!Treatment %in% c("BeforeExperiment", 
                           "GutHomFeedingSolution(SecondStep)", 
                           "GutHomogenate", 
                           "GlycerolPBScontrol(FirstStep)", 
                           "ControlFeedingSolution(SecondStep)"))

overall_stats <- dt_clean %>%
  summarise(
    Median_Raw = median(copynum, na.rm = TRUE),
    Mean_Raw   = mean(copynum, na.rm = TRUE),
    SD_Raw     = sd(copynum, na.rm = TRUE),
    Min_Raw    = min(copynum, na.rm = TRUE),
    Max_Raw    = max(copynum, na.rm = TRUE),
    Mean_Log10 = mean(log10(copynum), na.rm = TRUE),
    SD_Log10   = sd(log10(copynum), na.rm = TRUE)
  )
```

## Statistics (linear mixed model)
### Using Unique Replicate as random effect
```{r}
dt <- dt %>% filter(!is.na(Antibiotic))
dt$UniqueReplicate <- paste(dt$Antibiotic, dt$Reinoculation, dt$Replicate, sep="_")
length(unique(dt$UniqueReplicate)) #verification

dt$Antibiotic <- factor(dt$Antibiotic, levels = c("Zero", "Low", "High"))
dt$Reinoculation <- factor(dt$Reinoculation)
dt$Reinoculation <- relevel(dt$Reinoculation, ref = "No")

dt$Treatment <- interaction(dt$Antibiotic, dt$Reinoculation, drop = TRUE)

#Testing treatment (3X2 levels)
m2 <- lmer(log10(copynum) ~ Treatment + (1|UniqueReplicate), data = dt)

#Antibiotic treatment (3 levels)
m3 <- lmer(log10(copynum) ~ Antibiotic + (1|UniqueReplicate), data = dt)

#Antibiotic treatment (2 levels)
m4 <- lmer(log10(copynum) ~ Reinoculation + (1|UniqueReplicate), data = dt)

```

# Visualisation of qPCR
```{r}
p2 <- ggplot(dt, aes(x = Antibiotic, y = log10(copynum), fill = Reinoculation)) +
  geom_boxplot(alpha = 0.7, outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  labs(
       x = "Antibiotic dose",
       y = "Log10(Copies qPCR)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(p2)
```

## Save the plots

```{r}

results_dir <- here::here("qpcr", "result")

if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}

ggsave(file.path(results_dir, "qPCR_exploratory_plot.pdf"), plot = p1, width = 16, height = 4)
ggsave(file.path(results_dir, "qPCR_by_treatment.pdf"),       plot = p2, width = 8,  height = 4)

output_file <- file.path(results_dir, "qpcr_result.txt")

sink(output_file, append=FALSE)

print(summary(m2))
print(Anova(m2, type = "III"))

print(summary(m3))
print(Anova(m3, type = "III"))

print(summary(m4))
print(Anova(m4, type = "III"))

sink()

```


## Session info

```{r}
sessionInfo()
```