
## Load library
```{r}
library(readr)    
library(dplyr)      
library(lme4)       
library(lmerTest)   
library(DHARMa) 
library(emmeans)
library(ggplot2)  
library(ggbeeswarm)
library(car)

```

## Set working directory

```{r}
setwd("~/Desktop/simon_lasio/data/behavior and activity/tracking/interind_dist")
```


## Load and prepare data

```{r}
# === Paramètres ===
file <- "animal_ta_inderind_processed_with_arena.csv"
delim <- ";"                                      
decimal_mark <- ","             

# === Read the csv file ===

data_raw <- read_delim(file,
                       delim = delim,
                       locale = locale(decimal_mark = decimal_mark),
                       trim_ws = TRUE,
                       col_names = TRUE,
                       progress = FALSE,
                       guess_max = 2000)


data <- data_raw %>%
  mutate(
    Treatment = factor(Treatment),      
    Treatment = relevel(Treatment, ref = "zero_no"),
    Antibiotic = factor(Antibiotic),
    Antibiotic = relevel(Antibiotic, ref = "zero"),
    Reinoculation = factor(Reinoculation),
    Reinoculation = relevel(Reinoculation, ref = "no"),
    Year = factor(Year)   
  )

data$Antibiotic <- factor(data$Antibiotic, levels = c("zero", "low", "high"))

# Vérification
levels(data$Treatment)

```


## DESCRIPTIVES STATISTICS
```{r}
moyenne_Mean_dist <- tapply(data$Mean_dist, data$Treatment, mean, na.rm = TRUE)
ecarts_Mean_dist <- tapply(data$Mean_dist, data$Treatment, sd, na.rm = TRUE)

resultats_mean_dist <- data.frame(
  Moyenne_cm = moyenne_Mean_dist,
  Ecart_Type_cm = ecarts_Mean_dist
)

resultats_mean_dist
```

## Export descriptive stats

```{r}
write.csv(resultats_mean_dist, "table_dist_interind.csv", row.names = TRUE)
```


## LMM model 
```{r}
hist(data$Mean_dist, breaks = 15)
qqnorm(data$Mean_dist)

#fit the model
model_gauss <- lmer(Mean_dist ~ Antibiotic * Reinoculation + (1 | Year),data = data)

#residuals tests
simulateResiduals(model_gauss) |> plot()
testDispersion(model_gauss)
testResiduals(model_gauss)

a1 <- Anova(model_gauss, type = "III") 
a1

s1 <- summary(model_gauss)
s1

emm <- emmeans(model_gauss, ~ Antibiotic * Reinoculation)
emm_df <- as.data.frame(emm)
pairs(emm)
```

### Visualisation
```{r}

emm <- emmeans(model_gauss, ~ Antibiotic * Reinoculation)
emm_df <- as.data.frame(emm)
pairs(emm)


p1 <- ggplot() +
  # A. IC
  geom_rect(data = emm_df,
            aes(xmin = as.numeric(Antibiotic) - 0.3,
                xmax = as.numeric(Antibiotic) + 0.3,
                ymin = lower.CL,  
                ymax = upper.CL,  
                fill = Reinoculation),
            alpha = 0.3, 
            position = position_dodge(width = 0.8),
            show.legend = FALSE) + 

  # B. Predicted mean
  geom_errorbar(data = emm_df,
                aes(x = Antibiotic, 
                    ymin = emmean, 
                    ymax = emmean,
                    color = Reinoculation),
                width = 0.5, 
                position = position_dodge(width = 0.8), 
                size = 1.2) +
  
  # C. Raw data
  geom_beeswarm(data = data,
                aes(x = Antibiotic, 
                    y = Mean_dist, 
                    color = Reinoculation),
                dodge.width = 0.8, 
                cex = 1.2,        # Taille de dispersion
                size = 1.5,       # Taille des points
                alpha = 0.4) +    # Transparence 

  theme_bw() +
  labs(y = "Mean interindividual distance [cm]", 
       x = "Antibiotic dose",
       color = "Reinoculation",
       fill = "Reinoculation") 

print(p1)


```


### Save the plot 
```{r}
ggsave("mean_interind_full_plot.pdf", p1, width = 12, height = 8)
```


### additive model (Just to have it - The interaction is significant)
```{r}
model_gauss_add <- lmer(Mean_dist ~ Antibiotic + Reinoculation + (1 | Year),data = data)
simulateResiduals(model_gauss_add) |> plot()
testDispersion(model_gauss_add) 
testResiduals(model_gauss_add) 

summary(model_gauss_add)
Anova(model_gauss, type = "III") 


anova(model_gauss, model_gauss_add)
```






# Reduced model 
```{r}
# joining LOW and ZERO
data_raw <- read_delim(file,
                       delim = delim,
                       locale = locale(decimal_mark = decimal_mark),
                       trim_ws = TRUE,
                       col_names = TRUE,
                       progress = FALSE,
                       guess_max = 2000)

data_raw$Antibiotic <- as.character(data_raw$Antibiotic)
data_raw$Antibiotic[data_raw$Antibiotic %in% c("low", "zero")] <- "zero"

data_raw<- data_raw %>%
  mutate(Treatment = paste(Antibiotic, Reinoculation, sep = "_"))

data_low <- data_raw %>%
  mutate(
    Treatment = factor(Treatment),              
    Treatment = relevel(Treatment, ref = "zero_no"),
    Antibiotic = factor(Antibiotic),
    Antibiotic = relevel(Antibiotic, ref = "zero"),
    Reinoculation = factor(Reinoculation),
    Reinoculation = relevel(Reinoculation, ref = "no"),
    Year = factor(Year)   
  )


levels(data_low$Treatment)

```
## LMM model on 2x2 
```{r}
hist(data_low$Mean_dist, breaks = 15)
qqnorm(data_low$Mean_dist)

model_gauss_low <- lmer(Mean_dist ~ Antibiotic * Reinoculation + (1 | Year),data = data_low)
simulateResiduals(model_gauss_low) |> plot()
testDispersion(model_gauss_low)
testResiduals(model_gauss_low)

s2 <- summary(model_gauss_low)
s2
a2 <- a1 <- Anova(model_gauss_low, type = "III") 
a2

emm <- emmeans(model_gauss_low, ~ Antibiotic * Reinoculation)
emm_df <- as.data.frame(emm)
pairs(emm)
```

### Visualisation
```{r}

emm <- emmeans(model_gauss_low, ~ Antibiotic * Reinoculation)
emm_df <- as.data.frame(emm)
pairs(emm)


p2 <- ggplot() +
  # A. IC
  geom_rect(data = emm_df,
            aes(xmin = as.numeric(Antibiotic) - 0.3,
                xmax = as.numeric(Antibiotic) + 0.3,
                ymin = lower.CL,  
                ymax = upper.CL,  
                fill = Reinoculation),
            alpha = 0.3, 
            position = position_dodge(width = 0.8),
            show.legend = FALSE) + 

  # B. Predicted mean
  geom_errorbar(data = emm_df,
                aes(x = Antibiotic, 
                    ymin = emmean, 
                    ymax = emmean,
                    color = Reinoculation),
                width = 0.5, 
                position = position_dodge(width = 0.8), 
                size = 1.2) +
  
  # C. Raw data
  geom_beeswarm(data = data_low,
                aes(x = Antibiotic, 
                    y = Mean_dist, 
                    color = Reinoculation),
                dodge.width = 0.8, 
                cex = 1.2,        # Taille de dispersion
                size = 1.5,       # Taille des points
                alpha = 0.4) +    # Transparence 

  theme_bw() +
  labs(y = "Mean interindividual distance [cm]", 
       x = "Antibiotic dose",
       color = "Reinoculation",
       fill = "Reinoculation") 

print(p2)
```
### Save the plot 
```{r}
ggsave("mean_interind_reduced_plot.pdf", p2, width = 12, height = 8)
```



### additive model
```{r}
model_gauss_low_add <- lmer(Mean_dist ~ Antibiotic + Reinoculation + (1 | Year),data = data_low)
simulateResiduals(model_gauss_low_add) |> plot()
testDispersion(model_gauss_low_add); 
testResiduals(model_gauss_low_add) # tests supplémentaires

summary(model_gauss_low_add)
anova(model_gauss_low_add)
```


# Save the result in a .txt file

```{r}
sink("interind_dist_result.txt", split = TRUE)

cat("Interind dist for full 3x2 model\n\n")
a1 
s1

cat("Interind dist for reduced 2x2 model\n\n")
a2
s2

sink()
```
