# Load packages

```{r}
library(readxl)
library(here)
library(tidyverse)
library(dplyr)
library(survival)
library(survminer)
library(ggplot2)
library(purrr)
```

# Set working directory

```{r}
setwd("~/Desktop/simon_lasio/data/survival analysis")
```

# Preprocess the data 
```{r}
file_2024 <- here::here("survival_2024_with_pd_number.xlsx")
file_2025 <- here::here("survival_2025_with_pd_number.xlsx")

tableau_2024 <- read_excel(file_2024)
tableau_2025 <- read_excel(file_2025)

transform_survival <- function(df, year_val) {
  time_row <- df %>% 
    filter(str_detect(tolower(Category), "time"))
  
  time_dict <- tibble(
    column_name = colnames(df)[3:ncol(df)],
    time_hours = as.numeric(time_row[1, 3:ncol(df)])
  ) %>% filter(!is.na(time_hours)) 
  
  data_clean <- df %>%
    filter(!is.na(Category), !str_detect(tolower(Category), "time")) %>%
    rename(Petridish_number = `Petridish number`) %>%
    mutate(across(3:ncol(df), ~as.numeric(as.character(.))))
  
  data_long <- data_clean %>%
    pivot_longer(
      cols = any_of(time_dict$column_name),
      names_to = "column_name",
      values_to = "alive_count"
    ) %>%
    left_join(time_dict, by = "column_name") %>%
    filter(!is.na(alive_count)) %>%
    arrange(Category, Petridish_number, time_hours)
  
  survival_events <- data_long %>%
    group_by(Category, Petridish_number) %>%
    mutate(
      new_dead = lag(alive_count, default = first(alive_count)) - alive_count,
      new_dead = if_else(new_dead < 0, 0, new_dead)
    ) %>%
    ungroup()
  
  morts <- survival_events %>%
    filter(new_dead > 0) %>%
    uncount(new_dead) %>% 
    mutate(status = 1, time = time_hours)
  
  censures <- survival_events %>%
    group_by(Category, Petridish_number) %>%
    slice_tail(n = 1) %>% 
    ungroup() %>%
    filter(alive_count > 0) %>%
    uncount(alive_count) %>% 
    mutate(status = 0, time = time_hours)
  
  final_df <- bind_rows(morts, censures) %>%
    mutate(
      Category_base = str_trim(tolower(Category)),
      Antibiotic = case_when(
        str_detect(Category_base, "high") ~ "high",
        str_detect(Category_base, "low") ~ "low",
        TRUE ~ "no"
      ),
      Reinoculation = if_else(str_detect(Category_base, "gut|homogenate"), "yes", "no"),
      Treatment = paste0(Antibiotic, "_", Reinoculation),
      Year = year_val
    ) %>%
    select(Category_base, Antibiotic, Reinoculation, Year, Petridish_number, time, status, Treatment)
  
  return(final_df)
}

survie_2024 <- transform_survival(tableau_2024, 2024)
survie_2025 <- transform_survival(tableau_2025, 2025)
dataset_final <- bind_rows(survie_2024, survie_2025)

#write_csv(dataset_final, "surv_data.csv")

surv_individual <- dataset_final %>%
  mutate(
    Treatment = factor(Treatment),
    Treatment = relevel(Treatment, ref = "no_no"),
    Antibiotic = factor(Antibiotic, levels = c("no", "low", "high")),
    Reinoculation = factor(Reinoculation),
    Reinoculation = relevel(Reinoculation, ref = "no"),
    Year = factor(Year),
    Petridish_number = factor(Petridish_number))
```

# Fit a survival curve using the Kaplan-Meier method

```{r}
fit_ant <- survfit(Surv(time, status) ~ Antibiotic, type = "kaplan-meier", data=surv_individual)
fit_reino <- survfit(Surv(time, status) ~ Reinoculation, type = "kaplan-meier", data=surv_individual)
fit_inter <- survfit(Surv(time, status) ~ Treatment, type = "kaplan-meier", data=surv_individual)
```

# Log-Rank Test

```{r}
surv_diff_ant <- survdiff(Surv(time, status) ~ Antibiotic, data = surv_individual)
surv_diff_reino <- survdiff(Surv(time, status) ~ Reinoculation, data = surv_individual)
surv_diff_inter <- survdiff(Surv(time, status) ~ Treatment, data = surv_individual)
```

# Create the plots

```{r}
temps_2024 <- c(0, 4, 21, 24, 26.5, 28.5, 45, 48, 50.5, 52.5, 69, 72, 115.5, 117, 118)
temps_2025 <- c(0, 15, 18, 21, 24, 39, 42, 45, 48, 63, 66, 69, 72, 135, 138)

p_ant <- ggsurvplot(
  fit_ant,
  pval = TRUE,
  pval.size = 5,
  pval.method = TRUE,
  conf.int = FALSE,
  censor = FALSE,     
  surv.scale = "percent",
  xlab = "Time [h]",
  ylab = "Survival probability",
  

  ggtheme = theme_classic(), 
  legend.title = "Antibiotic dose",
  palette = c("#fcca46", "#fe7f2d", "#233d4d"), 
  linewidth = 1,
  alpha = 0.65
)

heures_observation <- sort(unique(c(temps_2024, temps_2025)))
df_surv <- surv_summary(fit_ant)

points_artificiels <- df_surv %>%
  group_by(strata) %>%
  do({
    strata_data <- .
    map_df(heures_observation, function(ch) {
      val_surv <- strata_data %>% filter(time <= ch) %>% slice_tail(n = 1)
      if(nrow(val_surv) == 0) {
        return(tibble(time = ch, surv = 1))
      } else {
        return(tibble(time = ch, surv = val_surv$surv))
      }
    })
  }) %>%
  ungroup()

p_ant$plot <- p_ant$plot +
  geom_point(
    data = points_artificiels, 
    aes(x = time, y = surv, color = strata), 
    shape = 4,       
    size = 1,        
    stroke = 0.8    
  ) +
  geom_vline(xintercept = 70, linetype = "dotted", linewidth = 0.7) +
  annotate(
    "text",
    x = 70, y = 0.20,
    label = "Re-inoculation",
    angle = 90,
    vjust = -0.5,
    color = "black",
    size = 4
  ) +

  
  theme(
    axis.line = element_line(color = "black"),
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    panel.grid.major.y = element_line(color = "grey95"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 11)
  )

# Afficher le résultat
print(p_ant)
```


```{r} 
p_reino <- ggsurvplot(
  fit_reino,
  title = "Impact of Re-inoculation on survival",
  pval = TRUE,
  pval.size = 7,
  pval.method = TRUE,
  conf.int = FALSE,
  surv.scale = "percent",
  xlab = "Time [h]",
  ylab = "Survival probability",
  ggtheme = theme_survminer(base_size = 8, base_family = "Helvetica"),
  legend.title = "Re-inoculation (yes/no)",
  palette = "Dark2",
  linewidth = 1.0,
  alpha = 0.8
)
p_reino$plot <- p_reino$plot +
  geom_vline(xintercept = 70, linetype = "dotted", size = 0.7) +
  annotate(
    "text",
    x = 70, y = 0.20,           # adjust y to be at top of plot
    label = "Re-inoculation",      # this will act as legend label
    angle = 90,
    vjust = -0.5,
    color = "black",
    size = 3
  )

p_reino


p_inter <- ggsurvplot(
  fit_inter,
  title = "Impact of Antibiotics and Re-inoculation on survival",
  pval = TRUE,
  pval.size = 6,
  pval.method = TRUE,
  conf.int = FALSE,
  surv.scale = "percent",
  xlab = "Time [h]",
  ylab = "Survival probability",
  ggtheme = theme_survminer(base_size = 8, base_family = "Helvetica"),
  legend.title = "Treatment",
  palette = "Dark2",
  linewidth = 1.0,
  alpha = 0.8
)
p_inter$plot <- p_inter$plot +
  geom_vline(xintercept = 70, linetype = "dotted", size = 0.7) +
  annotate(
    "text",
    x = 70, y = 0.20,           # adjust y to be at top of plot
    label = "Re-inoculation",      # this will act as legend label
    angle = 90,
    vjust = -0.5,
    color = "black",
    size = 3
  )
p_inter
```

# Save the plot

```{r}
ggsave("p_ant.pdf", dpi=300,  p_ant$plot,   width = 10, height = 5)
ggsave("p_reino.pdf", p_reino$plot, width = 8, height = 4)
ggsave("p_inter.pdf", p_inter$plot, width = 8, height = 4)
```

# Save the result in a .txt file

```{r}
output_file <- "survival_result.txt"
sink(output_file)

fit_ant
fit_reino
fit_inter
surv_diff_ant
surv_diff_ant$pvalue
surv_diff_reino
surv_diff_reino$pvalue
surv_diff_inter
surv_diff_inter$pvalue

sink()
```


# Justifying the joining of zero and low 
```{r}
survdiff(Surv(time, status) ~ Antibiotic, data = subset(surv_individual, Antibiotic %in% c("no", "low")))
```
